name: Update Treematic Installs Data

on:
  schedule:
    - cron: "0 22 * * *"  # Daily at 5 PM EST (10 PM UTC)
  workflow_dispatch:        # Manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: 80 perct Random Run Gate
        id: random_gate
        run: |
          VALUE=$((RANDOM % 10))
          if [ "$VALUE" -lt 2 ]; then
            echo "🎲 Skipping today's run (VALUE=$VALUE)"
            echo "run_today=false" >> $GITHUB_ENV
          else
            echo "🎯 Proceeding with today's run (VALUE=$VALUE)"
            echo "run_today=true" >> $GITHUB_ENV
          fi

      - name: Check for Install Updates
        if: env.run_today == 'true'
        id: check_update
        run: |
          LATEST_INSTALLED=$(curl -s https://raw.githubusercontent.com/jtroussard/treematic-stats/main/data.json | jq -r '.[-1].installs')
          CURRENT_INSTALLED=$(python run.py --check-only)

          echo "Latest Install Count: $LATEST_INSTALLED"
          echo "Current Install Count: $CURRENT_INSTALLED"

          if [ "$LATEST_INSTALLED" -eq "$CURRENT_INSTALLED" ]; then
            echo "No new installs. Skipping update."
            echo "update_needed=false" >> $GITHUB_ENV
            echo "$(date -u) UTC - No new installs detected." >> logs/update_log.txt
          else
            echo "New installs detected. Proceeding with update."
            echo "update_needed=true" >> $GITHUB_ENV
            echo "$(date -u) UTC - New installs detected. Updating data." >> logs/update_log.txt
          fi

      - name: Run Update Script
        if: env.update_needed == 'true'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python run.py

      - name: Commit and Push Data Changes
        if: env.update_needed == 'true'
        run: |
          git config user.name "Jacques Troussard"
          git config user.email "jacques.troussard@gmail.com"
          git add data.json
          git commit -m "Update Treematic Installs Data"
          git push

      - name: Commit and Push Log Updates
        if: env.run_today == 'true'
        run: |
          git config user.name "Jacques Troussard"
          git config user.email "jacques.troussard@gmail.com"
          git add logs/update_log.txt
          git commit -m "Log update: $(date -u +"%Y-%m-%d %H:%M:%S")"
          git push
